//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GenioAppEntities : DbContext
    {
        public GenioAppEntities()
            : base("name=GenioAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<HonorBoard> HonorBoards { get; set; }
        public virtual DbSet<Olimp> Olimps { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<StudentOlimp> StudentOlimps { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
