//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genio
{
    using System;
    using System.Collections.Generic;
    
    public partial class HonorBoard
    {
        public int honor_id { get; set; }
        public int student_id { get; set; }
        public System.DateTime placement_date { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
