//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Olimp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Olimp()
        {
            this.StudentOlimps = new HashSet<StudentOlimp>();
        }
    
        public int olimp_id { get; set; }
        public string olimp_name { get; set; }
        public System.DateTime olimp_date { get; set; }
        public int event_type_id { get; set; }
        public string olimp_level { get; set; }
        public string olimp_location { get; set; }
        public string nominations { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual EventType EventType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentOlimp> StudentOlimps { get; set; }
    }
}
